### ISSUE TITLE
Has anyone compiled it on Windows?

### ISSUE THREAD

**Issue by mazhongzhong** [vojirt/asms#1]
I've trying to compile this code on Windows. I used the cmake to successfully generate the VS2013 project(the openCV has also set correctly), but when I  compiled it with VS2013, it promoted folowing information：

1>------ Build started: Project: color, Configuration: Debug Win32 ------
1>cl : Command line error D8021: invalid numeric argument '/Wextra'
2>------ Build started: Project: asms_vot, Configuration: Debug Win32 ------
3>------ Build started: Project: demo, Configuration: Debug Win32 ------
2>cl : Command line error D8021: invalid numeric argument '/Wextra'
3>cl : Command line error D8021: invalid numeric argument '/Wextra'
========== Build: 0 succeeded, 3 failed, 2 up-to-date, 0 skipped ==========

Anyone knows how to fix this?

**Comment by vojirt** [comment]
Hi, this may be a problem with a compiler switches. Try to remove from CMakeList.txt line 5 the -Wextra flag and re-run the cmake and compile it again.

**Comment by lukacu** [comment]
The -Wextra flag is a GCC specific flag, [this](https://stackoverflow.com/questions/2274006/cmake-invalid-numeric-argument-wextra) is a similar issue.
