### ISSUE TITLE
Library not loaded: /usr/local/opt/jpeg/lib/libjpeg.8.dylib

### ISSUE THREAD

**Issue by minglinlu** [vojirt/asms#4]
dyld: Library not loaded: /usr/local/opt/jpeg/lib/libjpeg.8.dylib
  Referenced from: /usr/local/opt/opencv/lib/libopencv_highgui.2.4.dylib
  Reason: image not found
[1]    68180 abort      ./asms_trax

answer from:
http://blog.csdn.net/kingch_ban/article/details/77508796

> 
wget -c http://www.ijg.org/files/jpegsrc.v8d.tar.gz
tar xzf jpegsrc.v8d.tar.gz
cd jpeg-8d
./configure
make
cp ./.libs/libjpeg.8.dylib /usr/local/opt/jpeg/lib

**Comment by vojirt** [comment]
Hi, this is not problem with the code itself, but rather with your libraries/versions so I am closing this issue.
