### ISSUE TITLE
why variable j starts from x1 and ends at x1+1 when initializing?

### ISSUE THREAD

**Issue by liuchang988** [vojirt/asms#5]
In file colortracker.cpp, line 49:
`for (int j = x1; j < x1 + 1; j++) 
`

The variable j starts from x1 and ends at x1+1, code inside the loop only executes once. In the paper I did not find anything related to this, and the program runs well after i tried to modify x1 to x2. Is this a bug or a feature? If that is a feature, could anybody tell me why (or where in the paper)? Thanks!

**Comment by vojirt** [comment]
It is a bug, thank you for finding this out. Thankfully, this is not a crucial part of the algorithm, but rather just a way how to automatically set some thresholds, which are then check and clipped to a "valid" range.
